### ISSUE TITLE
Logout/invalidate token method

### ISSUE THREAD

**Issue by 54696d21** [lagmoellertim/freenet-funk-api#5]
Do you have any knowledge how the logout button of the app works?

**Comment by lagmoellertim** [comment]
Hi,
as far as I know, the token doesn't get invalidated  by the user.
Instead, the user is able to delete his session key (which automatically happens after the pythons script ends).
Then, after about an hour of inactivity, Amazon Cognito (the Authentication Provider) will invalidate the session key.
Because of this authentication flow, I don't see a benefit in adding e.g. a logout function to the code.
If you think otherwise, please reopen this issue.
